<input type="hidden" name="first_business_act" id="first_business_act" value="">
<input type="hidden" name="article_of_company" id="article_of_company" value="0">
<input type="hidden" name="csic_1" id="csic_1" value="">
<input type="hidden" name="csic_2" id="csic_2" value="">
<input type="hidden" name="csic_3" id="csic_3" value="">
<input type="hidden" name="csic_4" id="csic_4" value="">
<input type="hidden" name="csic_5" id="csic_5" value="">
<input type="hidden" name="business_activity" id="business_activity" value="">
<input type="hidden" name="business_activity1" id="business_activity1" value="">
<input type="hidden" name="business_activity2" id="business_activity2" value="">
<input type="hidden" name="business_activity3" id="business_activity3" value="">
<input type="hidden" name="business_activity4" id="business_activity4" value="">
<input type="hidden" name="company_register_number" id="company_register_number" value="">
<input type="hidden" name="registration_date" id="registration_date" value="">
<input type="hidden" name="company_tin" id="company_tin" value="">
<input type="hidden" name="nssf_number" id="nssf_number" value="">
<input type="hidden" name="single_id" id="single_id" value="">
<input type="hidden" name="operation_status" id="operation_status" value="">
<input type="hidden" name="company_id_auto" id="company_id_auto" value="0">
<input type="hidden" name="company_id" id="company_id" value="0">
<input type="hidden" name="company_id_lacms" id="company_id_lacms" value="0">
<input type="hidden" name="company_option" id="company_option" value="0">